# Generated by Django 3.1.4 on 2021-01-06 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speclization',
            new_name='specialization',
        ),
    ]
