# Generated by Django 3.1.4 on 2021-01-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seApp.doctor'),
        ),
    ]
