# Generated by Django 3.1.4 on 2021-01-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0002_auto_20210110_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
