# Generated by Django 3.1.4 on 2021-01-06 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0003_auto_20210106_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seApp.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seApp.user')),
            ],
        ),
    ]
