# Generated by Django 3.1.4 on 2021-01-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0004_auto_20210110_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], max_length=200, null=True),
        ),
    ]
