# Generated by Django 3.1.4 on 2021-01-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0004_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='specialization',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
