# Generated by Django 3.1.4 on 2021-01-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0005_auto_20210111_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='review',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
