# Generated by Django 3.1.4 on 2021-01-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0005_staff_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(choices=[('nurse', 'Nurse'), ('lab_specialist', 'Lab Specialist')], max_length=20, null=True),
        ),
    ]
