# Generated by Django 3.1.4 on 2021-01-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0005_auto_20210111_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
