# Generated by Django 3.1.4 on 2021-01-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0006_auto_20210107_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='medical_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
