# Generated by Django 3.1.4 on 2021-01-12 20:30

from django.db import migrations, models


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'admin'),
        Group(name=u'doctor'),
        Group(name=u'patient'),
        Group(name=u'staff'),
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'admin',
            u'doctor',
            u'patient',
            u'staff',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0007_auto_20210112_2230'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]