# Generated by Django 3.1.4 on 2021-01-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0007_auto_20210108_2114'),
        ('seApp', '0007_appointment_status'),
    ]

    operations = [
    ]
