# Generated by Django 3.1.4 on 2021-01-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0008_merge_20210108_2145'),
        ('seApp', '0008_merge_20210108_2138'),
    ]

    operations = [
    ]
