# Generated by Django 3.1.4 on 2021-01-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seApp', '0009_merge_20210108_2146'),
        ('seApp', '0008_merge_20210108_2128'),
    ]

    operations = [
    ]
